### ISSUE TITLE
Error on running scripts/get_motion_maps.py

### ISSUE THREAD

**Issue by sidsachan** [ShuaiBai623/AIC2021-T5-CLV#2]
The error:
0it [00:00, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/yaoy/anaconda3/envs/AIC2021-T5-CLV/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "scripts/get_motion_maps.py", line 32, in get_bk_map
    avg_img = np.mean(np.stack(imgs),0)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/yaoy/anaconda3/envs/AIC2021-T5-CLV/lib/python3.7/site-packages/numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/get_motion_maps.py", line 66, in <module>
    for imgs in tqdm(pool.imap_unordered(get_bk_map, files)):
  File "/home/yaoy/anaconda3/envs/AIC2021-T5-CLV/lib/python3.7/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/yaoy/anaconda3/envs/AIC2021-T5-CLV/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
ValueError: need at least one array to stack

In my understanding, this happens when some paths are incorrect. But I cannot figure out what is wrong. Any help is appreciated.

Thanks

**Comment by maria-zafar** [comment]
have you been able to find solution to this?

**Comment by MAHMOUDRR707** [comment]
@sidsachan @maria-zafar  The problem is sometimes it is add an ".ipycheckpoints"  to the path just you need to pop it from file list  before you  get into motion function
